version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: inventory-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  create-inventory:
    build: .
    container_name: create-inventory
    restart: always
    environment:
      DATABASE_URL: mysql+pymysql://user:password@db/inventory_db
      JWT_SECRET_KEY: supersecreto
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
